defaults: &default_settings
  aws_access_key_id: 'AKIAIO4ZPZLNHU3QUX5A'
  aws_secret_access_key: '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'
  associate_tag: 'puhsh-20'

development:
  <<: *default_settings
test:
  <<: *default_settings
sandbox:
  <<: *default_settings
production:
  <<: *default_settings
