development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: puhsh_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: puhsh_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: puhsh_production
  pool: 5
  username: root
  password: Puh5hd33b33!
  socket: /tmp/mysql.sock
