development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: puhsh_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: puhsh_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

sandbox:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: puhsh_sandbox
  host: 10.41.187.167
  port: 3306
  username: puhsh
  password: d13tp3ps11

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: puhsh_production
  host: puhsh.cnjjmtsvoavh.us-east-1.rds.amazonaws.com
  port: 3306
  username: puhsh
  password: d13tp3ps11
