development:
  host: 127.0.0.1
  port: 8080
  tracking_enabled: false
test:
  host: 127.0.0.1
  port: 8080
  tracking_enabled: false
sandbox:
  host: 127.0.0.1
  port: 8080
  tracking_enabled: false
production:
  host: 127.0.0.1
  port: 8080
  tracking_enabled: false
