development:
  notifications: 1
  email: 1
  events: 1
test:
  notifications: 1
  email: 1
  events: 1
sandbox:
  notifications: 1
  email: 1
  events: 1
production:
  notifications: 1
  email: 1
  events: 2
