s3_defaults: &default_settings
  access_key_id: 'AKIAJTARV35AERTENQ2A'
  secret_access_key: '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'

development:
  <<: *default_settings
  bucket: puhsh_development

test:
  <<: *default_settings
  bucket: puhsh_test

sandbox:
  <<: *default_settings
  bucket: puhsh_sandbox

production:
  <<: *default_settings
  bucket: puhsh_production
