s3_defaults: &default_settings
  access_key_id: 'AKIAJ7FV5OHECYWPCNDA'
  secret_access_key: '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'

development:
  <<: *default_settings
  bucket: puhsh_development

test:
  <<: *default_settings
  bucket: puhsh_test

production:
  <<: *default_settings
  bucket: puhsh
