s3_defaults: &default_settings
  access_key_id: 'AKIAJ7FV5OHECYWPCNDA'
  secret_access_key: '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'

development:
  <<: *default_settings
  bucket: puhsh_development
  url: ':s3_domain_url'

test:
  <<: *default_settings
  bucket: puhsh_test
  url: ':s3_domain_url'

sandbox:
  <<: *default_settings
  bucket: puhsh_sandbox
  url: ':s3_domain_url'

production:
  <<: *default_settings
  bucket: puhsh
  url: ':s3_alias_url'
  s3_host_alias: 'd1fakcx7ksmski.cloudfront.net'
