development:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
sandbox:
  solr:
    hostname: 10.41.187.169
    port: 8080
    log_level: WARNING
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
