development:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
sandbox:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    solr_home: solr
production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    solr_home: solr
